### ISSUE TITLE
Analizar tiempos de ejecución LCSS con PySpark

### ISSUE THREAD

**Issue by edoomm** [TT2024-B106/similarity-measures#38]

**Comment by MarcoOrtegaF** [comment]
El algoritmo LCSS (Longest Common Subsequence) no es ideal para implementarlo con PySpark debido a su naturaleza secuencial y dependiente de la comparación directa de elementos en dos secuencias. PySpark está diseñado para procesar datos en paralelo y distribuir la carga entre múltiples nodos, lo que no se alinea bien con el enfoque de comparación par-a-par del LCSS, donde cada elemento en una secuencia se compara con elementos específicos en otra. Esto puede llevar a un rendimiento subóptimo y a una complejidad de implementación mayor, ya que se requiere coordinar las comparaciones entre nodos y manejar las dependencias secuenciales, lo que va en contra del enfoque de procesamiento distribuido eficiente que ofrece PySpark.
